# Generated by Django 4.1.7 on 2023-03-09 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_collections', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('created_on', models.DateField(verbose_name='created on')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PortraitCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('save_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.allcollections')),
            ],
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterField(
            model_name='review',
            name='created_on',
            field=models.DateField(verbose_name='created on'),
        ),
        migrations.CreateModel(
            name='UploadPortrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('portrait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.portraitcollection')),
            ],
        ),
    ]
