# Generated by Django 4.1.7 on 2023-03-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_allcollections_portraitcollection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allcollections',
            old_name='all_collections',
            new_name='collection',
        ),
    ]
