# Generated by Django 4.1.7 on 2023-03-09 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_all_collections_allcollections_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcollections',
            name='url',
        ),
    ]
