# Generated by Django 4.1.7 on 2023-03-09 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_allcollections_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portraitcollection',
            name='save_collection',
        ),
        migrations.RemoveField(
            model_name='uploadportrait',
            name='portrait',
        ),
        migrations.DeleteModel(
            name='AllCollections',
        ),
        migrations.DeleteModel(
            name='PortraitCollection',
        ),
        migrations.DeleteModel(
            name='UploadPortrait',
        ),
    ]
