# Generated by Django 4.1.7 on 2023-03-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_portraitcollection_save_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.CharField(max_length=100)),
                ('created_on', models.DateField(verbose_name='created on')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
