# Generated by Django 4.1.7 on 2023-03-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_allcollections'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allcollections',
            options={},
        ),
        migrations.RemoveField(
            model_name='allcollections',
            name='created_on',
        ),
    ]
