# Generated by Django 4.1.7 on 2023-03-09 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_allcollections_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.allcollections')),
            ],
        ),
    ]
